### ISSUE TITLE
Implementation for VIM

### ISSUE THREAD

**Issue by CPerezz** [74th/vscode-monokaicharcoal#12]
I've been trying to find the same theme/colorschema for vim but haven't been able to.

Are there any plans to support it? I really love it and nothing feels as good as this when I used it in VSCode.

**Comment by 74th** [comment]
@CPerezz 
I am happy to have you say that.
I tried to convert to vim color schema with https://github.com/sickill/coloration.
Could you use this?
https://github.com/74th/vscode-monokaicharcoal/blob/master/themes/Monokai-Charcoal.vim

**Comment by 74th** [comment]
But, it does not seem easy.
![Screenshot from 2020-09-05 11-41-22](https://user-images.githubusercontent.com/1060011/92296215-1752d680-ef6d-11ea-9dd8-11b9a124e601.png)

**Comment by CPerezz** [comment]
Hey @74th sorry for the delay. I got this lost through all the notifications. I've been using the VIM theme and it works fine. Thanks a lot! Hope at some point I'm able to contribute to this since it's the best color schema for me.
