### ISSUE TITLE
No colour change in the Menu Bar

### ISSUE THREAD

**Issue by herpes-free-engineer-hpe** [74th/vscode-monokaicharcoal#13]
Issue Type: <b>Bug</b>

Hello,

The colour theme for the the Menu Bar is somehow not automatically enabled.

Please see the comparison below:

The snapshot of the Menu Bar from the extension website:

![image](https://user-images.githubusercontent.com/74726391/99689104-77dab580-2a7e-11eb-84d3-d998b663fdc3.png)

The snapshot of the Menu Bar from the local setup:

![image](https://user-images.githubusercontent.com/74726391/99688975-4e218e80-2a7e-11eb-9abc-5773cc460f91.png)

Extension version: 3.2.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 4.12.14-lp151.28.20-default openSUSE 15.1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz (24 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|23.52GB (2.40GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 79221ab9-1358-4969-a9e9-ca0ed90f37d0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by 74th** [comment]
It is `"window.titleBarStyle": "custom"`.

![Screenshot from 2020-11-20 19-08-16](https://user-images.githubusercontent.com/1060011/99788073-ed6c8180-2b63-11eb-835f-e7d53f0d3e68.png)

**Comment by 74th** [comment]
↑ to user setting.

**Comment by herpes-free-engineer-hpe** [comment]
Thank you very much!
