### ISSUE TITLE
Highlight opened file

### ISSUE THREAD

**Issue by tainbgo1** [74th/vscode-monokaicharcoal#15]
is there any way to highlight the opened file? I found that I have enabled the auto reveal function. But it did not work on monokai charcoal one.

**Comment by 74th** [comment]
In the next version, I made it look a little borderline.
![Screenshot from 2021-12-04 07-58-33](https://user-images.githubusercontent.com/1060011/144683603-60e4452b-dcae-490c-b825-1e2e35bed25d.png)
