### ISSUE TITLE
Unable to read Terminal colors

### ISSUE THREAD

**Issue by scorpion35** [74th/vscode-monokaicharcoal#16]
First of all, thank you very much for the extension! Has nice contrast all over. 

Noticed terminal colors need some love
![image](https://user-images.githubusercontent.com/18679225/121698657-35210f00-ca9c-11eb-8e68-1029a98ed071.png)

This is how it looks in iTerm
![image](https://user-images.githubusercontent.com/18679225/121699316-d314d980-ca9c-11eb-99ef-cac5fbff390a.png)

I am not sure which settings to override to show contrast in terminal. Can you help me fix it please

**Comment by 74th** [comment]
Thanks for using it.
I have tuned the powerline text color to be better in the background color instead of the foreground color.
As for the terminal, try using "workbench.colorCustomizations" to reconfigure a better color for yourself.
