### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vedant-jad99** [74th/vscode-monokaicharcoal#20]
The theme doesn't look the same on vim as it does in vs code. What are the steps for setting this theme in vim?

**Comment by 74th** [comment]
Are you using this one?

https://github.com/74th/vscode-monokaicharcoal/blob/master/themes/Monokai-Charcoal.vim

This is just a color assignment and does not guarantee that the color will be the same in VS Code and Vim, which have different Syntax Highlight mechanisms.
