### ISSUE TITLE
Comments are too bright 

### ISSUE THREAD

**Issue by mazwrld** [74th/vscode-monokaicharcoal#8]
This theme is perfect I love how everything is italicized and the colours are amazing!

I just have some ideas that I think would make the theme even better.. 
1. The border is a bit too thick 
2. The comments are too bright and they often confuse me for code

**Comment by 74th** [comment]
Border size may be not changeable.
Let's customize for your need!
https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by mazwrld** [comment]
So I referred to it as monokai-charcoal(HC) and Monokai Charcoal high contrast they both don't seem to respond to comments color change. Does it have another name...

**Comment by 74th** [comment]
```json
{
    "editor.tokenColorCustomizations": {
        "[monokai-chacoral(HC)]": {
            "comments": "#FF0000"
        }
    }
}
```

<img width="591" alt="Screen Shot 2019-11-25 at 7 26 10" src="https://user-images.githubusercontent.com/1060011/69502644-e6ad2d80-0f54-11ea-80f2-dac663047efa.png">

**Comment by 74th** [comment]
@doseofmazen
