### ISSUE TITLE
Styling for template strings?

### ISSUE THREAD

**Issue by kris10cabrera** [74th/vscode-monokaicharcoal#9]
Hi! Big fan of the `monokai-charcoal high contrast` color theme. I'm writing to request better styling for template strings. There's currently no differentiation b/w template strings and normal strings. the first screenshot is the current, the second is the desired effect 
<img width="143" alt="current template string preview" src="https://user-images.githubusercontent.com/40896596/72177702-43eb2a00-33af-11ea-8990-099003ee483d.png">
<img width="134" alt="desired type of template string preview" src="https://user-images.githubusercontent.com/40896596/72177705-464d8400-33af-11ea-8570-c48d12ed5b5a.png">

**Comment by 74th** [comment]
What language do you use? Would you tell me your code?
My Python format strings can be colored.
![Screenshot from 2020-01-11 08-20-21](https://user-images.githubusercontent.com/1060011/72193322-3c2d9300-344c-11ea-8130-7ebd23f29f0c.png)

**Comment by kris10cabrera** [comment]
JavaScript! and React @74th

**Comment by 74th** [comment]
@kris10cabrera It starts supporting javascript format string.
Please update this extension.
![screen1](https://user-images.githubusercontent.com/1060011/77729011-0bb7c700-7041-11ea-91a9-540e06f348d3.png)
